name: Packaging Tests

on:
  push:
    branches: "**"

  workflow_dispatch:

jobs:
  packaging_tests:
    name: test_packaging
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        packaging_docker_image:
          - citus/packaging:oraclelinux-7-pg
          - citus/packaging:oraclelinux-8-pg
          - citus/packaging:centos-7-pg
          - citus/packaging:centos-8-pg
        POSTGRES_VERSION:
          - 13
          - 14
          - 15
        include:
          - packaging_docker_image: citus/packaging:ubuntu-jammy-all
          - packaging_docker_image: citus/packaging:debian-bookworm-all
          - packaging_docker_image: citus/packaging:ubuntu-focal-all
          - packaging_docker_image: citus/packaging:debian-bullseye-all
          - packaging_docker_image: citus/packaging:ubuntu-bionic-all
          - packaging_docker_image: citus/packaging:debian-buster-all

    container:
      image: ${{ matrix.packaging_docker_image }}${{ matrix.POSTGRES_VERSION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add Postgres installation directory into PATH for rpm based distros
        run: |
          echo "/usr/pgsql-${{ matrix.POSTGRES_VERSION }}/bin" >> $GITHUB_PATH
        if: ${{ matrix.POSTGRES_VERSION != '' }}

      - name: Configure
        run: ./configure

      - name: Make
        run: make -sj$(cat /proc/cpuinfo | grep "core id" | wc -l)

      - name: Make install
        run: make install
